### ISSUE TITLE
Valid MongoDB connection string exposed in plaintext

### ISSUE THREAD

**Issue by cjgibson** [vibraneur-capstone/vape-sensor-inventory#19]
Just a heads - these are sufficient to access your database on Atlas:

https://github.com/vibraneur-capstone/vape-sensor-inventory/blob/85579d8e4c058070b265311f73108521349135f4/src/.env#L1

https://github.com/vibraneur-capstone/vape-sensor-inventory/blob/85579d8e4c058070b265311f73108521349135f4/src/repositories/mongo_config.py#L3

Tested by inserting a doc to a new db and collection:

```shell
MongoDB Enterprise cluster-vape-sensor-inventory-shard-0:PRIMARY> db.getSiblingDB("hello")["world"].find()
{ "_id" : ObjectId("5e3cb4d666f9fa4df195e6c2"), "example" : "doc" }
```

Doesn't look like the database itself has been used for much yet, but these credentials should be rotated as soon as is reasonable.

**Comment by BenxinNiu** [comment]
Thanks for the heads up. This is our capstone project and resources in these repos are for development purposes. By no means, these credentials will be used in production. Therefore we are well aware of this.

**Comment by BenxinNiu** [comment]
did not realize people would pay attention to his capstone. and accidentally left 0.0.0.0 network access open.

**Comment by cjgibson** [comment]
It's less "paying attention to the capstone" and more "developer opens [blog post at work](https://shhgit.darkport.co.uk/), forgets about it in a background tab for about an hour, and then notices what looks like a legitimate connection string".

It's generally good practice to close issues with an associated PR, but you've shut off the upstream database here entirely, which seems like a sufficient fix for now! 😀
